name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v1

    - name: Build Hugo
      uses: jakejarvis/hugo-build-action@v0.59.1
      env:
        HUGO_ENV: production
