# name of the action
name: build

# trigger on pull_request or push events
on:
  push:
  pull_request:

# pipeline to execute
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: clone
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: node
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.101.0'
        extended: true

    - name: build
      env:
        HUGO_ENV: production
      run: |
        hugo --minify
