# name of the action
name: publish

# trigger on push to main
on:
  push:
    branches:
      - main

# pipeline to execute
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: clone
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: node
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version: '18'

    - name: hugo
      uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v2
      with:
        hugo-version: '0.134.2'
        extended: true

    - name: build
      env:
        HUGO_ENV: production
        HUGO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install -D --save autoprefixer
        npm install -D --save postcss-cli
        hugo --minify

    - name: publish
      uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
