# name of the action
name: publish

# trigger on push to main
on:
  push:
    branches:
      - main

# pipeline to execute
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write

    steps:
    - name: clone
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.108.0'
        extended: true

    - name: build
      env:
        HUGO_ENV: production
        HUGO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install -D --save autoprefixer
        npm install -D --save postcss-cli
        hugo --minify

    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
