name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v1

    - name: Build Hugo
      uses: jakejarvis/hugo-build-action@v0.59.1
      env:
        HUGO_ENV: production

    - name: publish
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
